### ISSUE TITLE
Enum types for muSpec and spec

### ISSUE THREAD

**Issue by veith** [eclipse/eclipsefuro#10]
It would be nice to have enum support at some time. Sooner or later we need them.

Possible muspec file (valid)
```yaml
- type: 'enum.Corpus #enum sample with aliases'
  fields:
    corpus: |-
      enum:1 # This could be a enum muspec
      ---
      UNKNOWN: 0
      STARTED: 1
      RUNNING: 1
      COMPLETE: 2
  target: enum.proto
```

Possible spec file
```yaml
name: Corpus
type: Corpus
description: enum sample with aliases
lifecycle: null
__proto:
    package: enum
    targetfile: enum.proto
    imports: []
    options:
        go_package: enum/dist/pb/enum;enumpb
        java_multiple_files: "true"
        java_outer_classname: EnumProto
        java_package: com.example.tutorial.enum
fields:
    corpus:
        type: enum
        description: |-
            my description
        __proto:
            number: 1
            allow_alias: true
        __ui: null
        meta:
            typespecific:
                options:
                    COMPLETE: 2
                    RUNNING: 1
                    STARTED: 1
                    UNKNOWN: 0
        constraints: {}

```

Resulting Proto
```proto
// Code generated by furo-proto-gen. DO NOT EDIT.
syntax = "proto3";
package enum;
option go_package = "enum/dist/pb/enum;enumpb";
option java_multiple_files = true;
option java_outer_classname = "EnumProto";
option java_package = "com.example.tutorial.enum";


// enum sample with aliases
enum Corpus {
    option allow_alias = true;
    UNKNOWN = 0;
    STARTED = 1;
    RUNNING = 1;
}
```
