### ISSUE TITLE
Specification of the constraints for complex data types

### ISSUE THREAD

**Issue by maltenorstroem** [eclipse/eclipsefuro#21]
**Status quo**
No restrictions can be defined on complex data types at the field specification level. It is only possible to define the restrictions on the data type itself. However, these then apply to all fields of this type.

**Requested extension**
It should be possible for a complex data type to define restrictions on subfields. e.g.

```
- type: 'country.CountryReference #Use this to set a reference to a country'
  fields:
    id: '* string:1 #Id of the referenced country.'
    display_name: '* string:2 #Label of the referenced country'
    link: 'furo.Link:3 #HTS for the initial search. Using default values works on root resources only.'
  target: country.proto
```

```
smallest_neighbour_country:
        type: country.CountryReference
        meta:
            default: ""
            placeholder: ""
            hint: ""
            label: country.type.smallestneighbourcountry.label
            options:
                flags: []
                list: []
            readonly: false
            repeated: false
            typespecific: null
        constraints:
           id :
                required:
                is: "true"
                message: smallest_neighbour_country is required
           
```
This way it would be possible to specify individual restrictions on complex types.
This specification must then be taken into account in the checkConstraints of the data object.         
   
![Screenshot 2022-04-11 at 11 37 58](https://user-images.githubusercontent.com/9052672/162711284-dba263ef-4438-4a6b-b730-d837cd17724f.png)

**Comment by maltenorstroem** [comment]
This behaviour can be achieved in the following way:
```
smallest_neighbour_country:
        type: country.CountryReference
        meta:
            default: ""
            placeholder: ""
            hint: ""
            label: country.type.smallestneighbourcountry.label
            options:
                flags: []
                list: []
            readonly: false
            repeated: false
            typespecific: null
        constraints:
           id.required:
                is: "true"
                message: smallest_neighbour_country is required
```
